<?xml version="1.0" ?>
<robot name="dual_arm_ur5" xmlns:xacro="http://ros.org/wiki/xacro">
	
  <!-- common stuff -->
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/ur5/ur5.gazebo.urdf.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/ur5/ur5.urdf.xacro" />
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/ur5/ur5.transmission.xacro" />
	
 <!--Pr2 gripper -->
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/gripper_v0/gripper.urdf.xacro" />
	
 <property name="M_PI" value="3.14159"/>
	<!-- property list -->
	
	<xacro:property name="robot_stand_height" value="0.75"/>
	<xacro:property name="kinect_stand_length" value="1.5"/>
	<xacro:property name="kinect_stand_distance" value="0.10"/>
	<xacro:ur5_robot prefix="right_" joint_limited="false"/>
	<xacro:ur5_robot prefix="left_" joint_limited="false"/>
	
	<!-- color macros -->
	
	
	<xacro:macro name="material_orange_transparent">
		<material name="orange_transparent">
			<color rgba="1 0.5 0 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_blue_transparent">
		<material name="blue_transparent">
			<color rgba="0 0.8 1 0.4"/>
		</material>
	</xacro:macro>
	
	<xacro:material_orange_transparent />
	
	<xacro:material_blue_transparent />
	<!-- end of color macros -->

	
	<link name="world"/>
	<link name="stand1">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	
	<link name="stand2">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/2}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/2}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	<!-- fixing barrett hand to the ur5 -->
	
        
	
	
	<!-- Hand attached to the arm -->

	<joint name="world_to_stand" type="fixed">
		<parent link="world"/>
		<child link="stand1"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</joint>

	<joint name="stand1_to_stand2" type="fixed">
		<parent link="stand1"/>
		<child link="stand2"/>
		<origin xyz="0 0 ${robot_stand_height/2}" rpy="0 1.57 0"/>
	</joint>
	
	
	<joint name="stand2_to_right_arm" type="fixed">
		<parent link="stand2"/>
		<!--child link="${arm_prefix}base_link"/-->
		<child link="right_base_link"/>
		<origin xyz="0 0 ${robot_stand_height/4}" rpy="0 0 ${M_PI/2}"/>
	</joint>

	<joint name="stand2_to_left_arm" type="fixed">
		<parent link="stand2"/>
		<!--child link="${arm_prefix}base_link"/-->
		<child link="left_base_link"/>
		<origin xyz="0 0 -${robot_stand_height/4}" rpy="0 ${M_PI} -${M_PI/2}"/>
	</joint>

	
		
	
</robot>
