<?xml version="1.0" ?>
<robot name="dual_arm_ur5" xmlns:xacro="http://ros.org/wiki/xacro">
	
  <!-- common stuff -->
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/ur5/ur5.gazebo.urdf.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/ur5/ur5.urdf.xacro" />
  <xacro:include filename="$(find dual_arm_ur5_description)/urdf/ur5/ur5.transmission.xacro" />
	
 <!-- PR2 gripper -->
  <xacro:include filename="$(find pr2_description)/urdf/gripper_v0/gripper.urdf.xacro" />


 <property name="M_PI" value="3.14159"/>
	<!-- property list -->
	
	<xacro:property name="robot_stand_height" value="1"/>
	<xacro:ur5_robot prefix="r_" joint_limited="false"/>
	<xacro:ur5_robot prefix="l_" joint_limited="false"/>
	
	<!-- color macros -->
	
	
	<xacro:macro name="material_orange_transparent">
		<material name="orange_transparent">
			<color rgba="1 0.5 0 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_blue_transparent">
		<material name="blue_transparent">
			<color rgba="0 0.8 1 0.4"/>
		</material>
	</xacro:macro>
	
	<xacro:material_orange_transparent />
	
	<xacro:material_blue_transparent />
	<!-- end of color macros -->

	
	<link name="world"/>
	<link name="base_link"/>
	
	<link name="stand1">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	
	<link name="stand2">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/1.5}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/1.5}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>

	<link name="stand3">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/4}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/4}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>

	<link name="stand4">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/4}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height/4}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	<!-- fixing barrett hand to the ur5 -->
	
        
	
	
	<!-- Hand attached to the arm -->
	<joint name="world_to_base_link" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</joint>	

	<joint name="base_link_to_stand" type="fixed">
		<parent link="base_link"/>
		<child link="stand1"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</joint>

	<joint name="stand1_to_stand2" type="fixed">
		<parent link="stand1"/>
		<child link="stand2"/>
		<origin xyz="0 0 ${robot_stand_height/2}" rpy="1.57 1.57 0"/>
	</joint>

	<joint name="stand2_to_stand3" type="fixed">
		<parent link="stand2"/>
		<child link="stand3"/>
		<origin xyz="-0.05 0 ${(robot_stand_height/4)+0.15}" rpy="0 1.57 0"/>
	</joint>
	
	<joint name="stand2_to_stand4" type="fixed">
		<parent link="stand2"/>
		<child link="stand4"/>
		<origin xyz="-0.05 0 -${(robot_stand_height/4)+0.15}" rpy="0 1.57 0"/>
	</joint>
	
	
	<joint name="stand3_to_right_arm" type="fixed">
		<parent link="stand3"/>
		<!--child link="${arm_prefix}base_link"/-->
		<child link="r_base_link"/>
		<origin xyz="0 0 -${robot_stand_height/8}" rpy="0 ${M_PI} -${M_PI/2}"/>
	</joint>

	<joint name="stand4_to_left_arm" type="fixed">
		<parent link="stand4"/>
		<!--child link="${arm_prefix}base_link"/-->
		<child link="l_base_link"/>
		<origin xyz="0 0 -${robot_stand_height/8}" rpy="0 ${M_PI} -${M_PI/2}"/>
	</joint>

	<xacro:pr2_gripper_v0 reflect="-1.0" side="r" parent="r_ee_link"
               screw_reduction="${4.0/1000.0}"
               gear_ratio="${(729.0/25.0)*(22.0/16.0)}"
               theta0="${3.6029*M_PI/180.0}"
               phi0="${29.7089*M_PI/180.0}"
               t0="${-0.1914/1000.0}"
               L0="${37.5528/1000.0}"
               h="${0.0/1000.0}"
               a="${68.3698/1000.0}"
               b="${43.3849/1000.0}"
               r="${91.5/1000.0}" >
    <origin xyz="-0.0285 0 0" rpy="0 0 0" />
  </xacro:pr2_gripper_v0>

	<xacro:pr2_gripper_v0 reflect="1.0" side="l" parent="l_ee_link"
               screw_reduction="${4.0/1000.0}"
               gear_ratio="${(729.0/25.0)*(22.0/16.0)}"
               theta0="${3.6029*M_PI/180.0}"
               phi0="${29.7089*M_PI/180.0}"
               t0="${-0.1914/1000.0}"
               L0="${37.5528/1000.0}"
               h="${0.0/1000.0}"
               a="${68.3698/1000.0}"
               b="${43.3849/1000.0}"
               r="${91.5/1000.0}" >
    <origin xyz="-0.0285 0 0" rpy="0 0 0" />
  </xacro:pr2_gripper_v0>

	
		
	
</robot>
